### ISSUE TITLE
Confirm this plugin works with wildcard spec parameter

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-split#10]
```yml
- name: Run bonus tests 🧪
  # https://github.com/cypress-io/github-action
  uses: cypress-io/github-action@v4
  with:
    spec: 'cypress/integration/bonus*.js'
  env:
    SPLIT: ${{ strategy.job-total }}
    SPLIT_INDEX: ${{ strategy.job-index }}
```

**Comment by dannyskoog** [comment]
Hi @bahmutov. I can confirm that this does **not** work. In my case my step looks like this:

```yaml
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        install: false
        start: npx serve -l 8080
        wait-on: http://localhost:8080
        browser: chrome
        spec: cypress/e2e/staging/**/*.spec.ts
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}
        SERVICE_ACCOUNT: ${{ secrets.FIREBASE_ADMIN_SA_STAGE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But specs outside of the `staging` folder where ran anyway

**Comment by dannyskoog** [comment]
What **did work**, though, was using the `config.specPattern` parameter, i.e:

```yaml
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        install: false
        start: npx serve -l 8080
        wait-on: http://localhost:8080
        browser: chrome
        config: specPattern=cypress/e2e/staging/**/*.spec.ts
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}
        SERVICE_ACCOUNT: ${{ secrets.FIREBASE_ADMIN_SA_STAGE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by bahmutov** [comment]
Yup, Cypress does not pass `spec` CLI argument anywhere, thus this plugin has no idea what to do, there is an issue I opened https://github.com/cypress-io/cypress/issues/26032

I think for now I will work around it by asking the to pass the `spec` argument via env variable too, something like

```yml
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        install: false
        start: npx serve -l 8080
        wait-on: http://localhost:8080
        browser: chrome
        spec: cypress/e2e/staging/**/*.spec.ts
      env:
        SPLIT: ${{ strategy.job-total }}
        SPLIT_INDEX: ${{ strategy.job-index }}
        SPLIT_SPECS: cypress/e2e/staging/**/*.spec.ts
```
