### ISSUE TITLE
Plugin Error: Help needed ⚙️

### ISSUE THREAD

**Issue by muriukialex** [bahmutov/cypress-split#140]
Below is an error I get after using the `cypress-split` package to run my cypress tests for my GitHub actions workflow

#### Here's the error

```json

cypress-split shouldWriteSummary true +46ms

Could not find spec results for a/a.spec.js
Could not find spec results for a/b.spec.js
Could not find spec results for accounts/a.spec.js
Could not find spec results for analytics/a.spec.js
Could not find spec results for apiKeys/a.spec.js
Could not find spec results for banners/a.spec.js
Could not find spec results for billing/a.spec.js
Could not find spec results for billing/b.spec.js
Could not find spec results for billing/c.spec.js
Could not find spec results for billing/d.spec.js
Could not find spec results for billing/e.spec.js
Could not find spec results for billing/f.spec.js
Could not find spec results for billing/g.spec.js
Could not find spec results for blockContactUpdate/a.spec.js
Could not find spec results for blocklist/a.spec.js
Could not find spec results for contacts/a.spec.js
Could not find spec results for contacts/b.spec.js
Could not find spec results for contacts/c.spec.js
Could not find spec results for contacts/d.spec.js
Could not find spec results for contacts/e.spec.js
Could not find spec results for contacts/f.spec.js
Could not find spec results for contacts/g.spec.js
Could not find spec results for contacts/h.spec.js
Could not find spec results for contacts/i.spec.js
Could not find spec results for contacts/j.spec.js
Could not find spec results for contacts/k.spec.js
Could not find spec results for contacts/l.spec.js
Could not find spec results for contacts/m.spec.js
Could not find spec results for contacts/n.spec.js
Could not find spec results for contacts/o.spec.js
Could not find spec results for enterprise/a.spec.js
Could not find spec results for enterprise/b.spec.js
Could not find spec results for expiredSession/a.spec.js
Could not find spec results for groups/a.spec.js
Could not find spec results for groups/b.spec.js
Could not find spec results for groups/c.spec.js
Could not find spec results for groups/d.spec.js
Could not find spec results for groups/e.spec.js

An error was thrown in your plugins file while executing the handler for the 'after:run' event.


An error was thrown in your plugins file while executing the handler for the 'after:run' event.

The error we received was:

TypeError: Cannot destructure property 'header' of 'cell' as it is undefined.
    at /home/runner/work/smsl-frontend/smsl-frontend/dashboard/node_modules/@actions/core/src/summary.ts:238:20
    at Array.map (<anonymous>)
    at /home/runner/work/smsl-frontend/smsl-frontend/dashboard/node_modules/@actions/core/src/summary.ts:233:12
    at Array.map (<anonymous>)
    at Summary.addTable (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/node_modules/@actions/core/src/summary.ts:231:8)
    at Object.handler (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/node_modules/cypress-split/src/index.js:351:14)
    at invoke (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16)
    at /home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:45:14
    at tryCatcher (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:44:23)
    at wrapChildPromise (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:112:10)
    at execute (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:125:14)
    at EventEmitter.<anonymous> (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:202:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/home/runner/work/smsl-frontend/smsl-frontend/dashboard/$HOME/.cache/Cypress/7.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)

Error: The process '/opt/hostedtoolcache/node/18.18.0/x64/bin/npm' failed with exit code 1
```

I'm using cypress version `7.4.0` and the cypress-split version `1.13.0` 

```json
"devDependencies": {
"cypress": "^7.4.0",
 "cypress-split": "^1.13.0"
}
```

Here's the way I have my Github workflow code
```yml
 - name: Run server and tests
    uses: cypress-io/github-action@v2
    env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}
            DEBUG: cypress-split
     with:
            install: false
            working-directory: dashboard
            browser: ${{ matrix.browser }}
            config: baseUrl=${{ matrix.base-url }}, port= ${{ matrix.port }}
            command: npm run cypress
```

`npm run cypress` runs this script command 

```json
"scripts": {
  "cypress": "PORT=3001 npm run dev & npx cypress run",
}
```

Attached below is my Github workflow file for more context

```yml
name: Tests

on:
    push:
        branches:
            - development
            - master
            - staging
        paths:
            - 'dashboard/**'
    pull_request:
        branches:
            - development
            - master
            - staging
        paths:
            - 'dashboard/**'

jobs:
    cypress-run:
        name: Cypress run
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]
                directory:
                    - dashboard
                port:
                    - 3001
                base-url:
                    - http://localhost:3001
                browser:
                    - chrome

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v2

            - name: Update packages
              run: sudo apt-get update

            - name: Install Ubuntu deps
              run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  # node-version: ${{ matrix.node-version }}

            - name: Clear npm cache
              run: npm cache clean --force

            - name: Install dependencies
              run: npm install --legacy-peer-deps --verbose
              working-directory: dashboard

            - name: Check Cypress binary
              run: |
                  npx cypress cache path
                  npx cypress cache list

            - name: Print GitHub strategy context 🖨
              run: echo '${{ toJSON(strategy) }}'

            - name: Run server and tests
              uses: cypress-io/github-action@v2
              env:
                  SPLIT: ${{ strategy.job-total }}
                  SPLIT_INDEX: ${{ strategy.job-index }}
                  DEBUG: cypress-split
              with:
                  install: false
                  working-directory: dashboard
                  browser: ${{ matrix.browser }}
                  config: baseUrl=${{ matrix.base-url }}, port= ${{ matrix.port }}
                  command: npm run cypress
```

Any assistance with be well appreciated @bahmutov @vallme2003  @Baune8D

**Comment by bahmutov** [comment]
It seems, it does not properly find the specs, so the spec names are not absolute.
I added a fix, to be released soon.
BUT: you are using Cypress v7 that is _very very_ old. I would upgrade ASAP to the new Cypress version, ok.

**Comment by bahmutov** [comment]
Also: could you post the DEBUG logs? It seems you only have partial logs, I would like to see which specs it finds

**Comment by muriukialex** [comment]
> It seems, it does not properly find the specs, so the spec names are not absolute. I added a fix, to be released soon. BUT: you are using Cypress v7 that is _very very_ old. I would upgrade ASAP to the new Cypress version, ok.

Alright, my team and I have been contemplating doing the upgrade.

**Comment by muriukialex** [comment]
> Also: could you post the DEBUG logs? It seems you only have partial logs, I would like to see which specs it finds

Posting the logs in a bit.

Interestingly enough, after setting the `SPLIT_SUMMARY` yml env config to `false`, the error vanished

```yml
- name: Run server and tests
   uses: cypress-io/github-action@v6
   env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_SUMMARY: false # here
          DEBUG: cypress-split
   with:
          install: false
          working-directory: dashboard
          browser: ${{ matrix.browser }}
          config: baseUrl=${{ matrix.base-url }}, port= ${{ matrix.port }}
          command: npm run cypress
```
