### ISSUE TITLE
There is no printed output for durations of specs.

### ISSUE THREAD

**Issue by ngothanhtai** [bahmutov/cypress-split#144]
From the documentation:
`At the end of the run, the duration of all run specs is printed and can be saved into the timings JSON file`

But I don't see any logs in Github Actions.

Here is my workflow on Github Actions:
```yml
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          command: firebase emulators:exec --only database './test.sh'
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_FILE: cypress/timings.json
```

Here is the screenshot at the end of the run. I expect the output above the **(Run Finished)**
![image](https://github.com/bahmutov/cypress-split/assets/295174/80f4e885-0942-40f6-a897-edcb6162f2eb)
