### ISSUE TITLE
timings.json file not found while using cypress github action

### ISSUE THREAD

**Issue by pavelloz** [bahmutov/cypress-split#156]
Hello,

Im trying to use `cypress-split` with `timings.json` file.

I created `timings.json` in root directory, and tests are in `cypress/` - just like in the official example repository. ( https://github.com/bahmutov/cypress-split-timings-example/blob/main/.github/workflows/ci.yml#L24 + https://github.com/bahmutov/cypress-split-timings-example/blob/main/timings.json )

```
cypress-split: Could not split specs by duration
cypress-split: there are 29 found specs
cypress-split: chunk 3 of 3
cypress-split: specs from the current directory /home/runner/work/frontend/frontend/cypress
ENOENT: no such file or directory, open 'timings.json'
cypress-split: splitting as is by name
```

In the github action config file this is how i point to a file:

```
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          SPLIT_FILE: "timings.json" # split suite based on timings, not alphabetical
```

Additionally, inside the github action ive run `ls -la *.json` to make sure the file does exist and im not going crazy, and it looks like it is. Im kind of lost. I dont see any config option to change the root directory for cypress github action, so im not sure how it can miss the file.

![image](https://github.com/bahmutov/cypress-split/assets/546845/2c0bc715-7b6a-4158-a2d1-7321ed06e464)

For privacy reasons i cannot give URL to a repository, but if something comes to anyones mind i would be very grateful - maybe someone had similar issue, im out of ideas. :)
