### ISSUE TITLE
Plugin clears config.env.name

### ISSUE THREAD

**Issue by StefanTegeltija** [bahmutov/cypress-split#34]
Here is example: https://github.com/StefanTegeltija/cypress-split-env-config-issue

**Comment by bahmutov** [comment]
Ok, I got this.

When you use `cypress-io/github-action` (or my reusable workflows) it forms the `npx cypress run ...` command itself, passing all arguments (in reality it calls `require('cypress').run({ ... })`. Thus it has no idea that you want to call your custom npm script. If you want to call `run:dev`, then do

```yml
- name: Run split Cypress tests 🧪
  # https://github.com/cypress-io/github-action
  uses: cypress-io/github-action@v5
  with:
     command: npm run run:dev
  env:
    SPLIT: ${{ strategy.job-total }}
    SPLIT_INDEX: ${{ strategy.job-index }}
```

See https://github.com/cypress-io/github-action#custom-test-command
