### ISSUE TITLE
Cypress split is not splitting the tests with command: npx cypress run --env ENV=US --spec 'cypress/e2e/test-ci/' on GitHub Actions

### ISSUE THREAD

**Issue by kryvchenko** [bahmutov/cypress-split#372]
**For some reason cypress-split is not working in this case:**

```
name: Cypress Daily Tests

on:
  push:
    branches: add-cypress-split
  schedule:
    - cron: '00 03 * * *'
  workflow_dispatch:

jobs:
  cypress-acceptance-daily-run:
    timeout-minutes: 120
    runs-on: QARunner
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    container: cypress/base:latest
```

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
           SPLIT: ${{ strategy.job-total }}
           SPLIT_INDEX: ${{ strategy.job-index }}
        with:
          command: npx cypress run --env ENV=US --spec 'cypress/e2e/test-ci/' 
          

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-US
          path: cypress/screenshots
          retention-days: 7

If I remove these lines:
```
        with:
          command: npx cypress run --env ENV=US --spec 'cypress/e2e/test-ci/' 
```
It would work for all tests, but I don't want that. I need to run tests only from the specific folder.

Not sure that it is possible. I would appreciate some advice here.

**Comment by bahmutov** [comment]
Cypress does not pass the list of specs to its plugins, so this plugin does not "see" your command line argument `--spec 'cypress/e2e/test-ci/'`

You can tell this plugin which specs to split by passing the specs again via an env variable, see https://github.com/bahmutov/cypress-split?tab=readme-ov-file#list-of-specs

```yml
  - name: Run Cypress tests
    uses: cypress-io/github-action@v6
    env:
       SPLIT: ${{ strategy.job-total }}
       SPLIT_INDEX: ${{ strategy.job-index }}
       SPEC: 'cypress/e2e/test-ci/'
    with:
      command: npx cypress run --env ENV=US --spec 'cypress/e2e/test-ci/'
```
