### ISSUE TITLE
(1 of 2) Node 18 shows no specs to run with unknown spec name = empty-3-of-4.cy.js

### ISSUE THREAD

**Issue by bennymeade** [bahmutov/cypress-split#55]
Hi @bahmutov I'm raising 2 bugs that may or may not be related to each other.

I have created an example repo here: https://github.com/bennymeade/cypress-split-node-18-config-file/
Which is Node 18, yarn, typescript and cypress-split with 2 containers based.

In my workflow for Node 18 steps 'Run desktop tests' see here: https://github.com/bennymeade/cypress-split-node-18-config-file/actions/runs/4963303007/jobs/8882400118#step:5:80

Run command: `yarn cypress run --browser chrome`

```
  │ Cypress:        12.12.0                                                                        │
  │ Browser:        Chrome 113 (headless)                                                          │
  │ Node Version:   v18.16.0 (/opt/hostedtoolcache/node/18.16.0/x64/bin/node)                      │
  │ Specs:          1 found (empty-3-of-4.cy.js)                                                   │
  │ Searched:       /tmp/empty-3-of-4.cy.js     
```
No specs are found or run, but the build step still completes as success.

<img width="752" alt="image" src="https://github.com/bahmutov/cypress-split/assets/1033474/e9513b12-3bcd-4d29-9eb0-e35100a0b4db">

This is working fine on Node 16 see here: https://github.com/bennymeade/cypress-split-node-18-config-file/actions/runs/4963303007/jobs/8882400034#step:5:84

**Comment by bennymeade** [comment]
Hi @bahmutov did you get an opportunity to run my repo example?

**Comment by bahmutov** [comment]
ok, let me check

**Comment by bahmutov** [comment]
Ok, here is what is happening. You want to run all specs on Node 16. And you also want to run all specs on Node 18. BUT this matrix configuration creates a single 4 container workflow right?
```yml
strategy:
  fail-fast: false
  matrix:
    os: [ubuntu-latest]
    node: [16, 18]
    containers: [1, 2]
```
So 4 containers start in parallel

<img width="1046" alt="Screenshot 2023-05-19 at 16 53 16" src="https://github.com/bahmutov/cypress-split/assets/2212006/dddb3280-f8e7-4d27-800d-ab46ce43070d">

Cypress split gets only 2 numbers from the workflow:
```yml
env:
    SPLIT: ${{ strategy.job-total }}
    SPLIT_INDEX: ${{ strategy.job-index }}
```
The total number of containers is 4. The index is 0, 1, 2, 3
There are 2 specs, so the first container Node v16 gets spec 1. The second _Node v16_ container gets spec 2. The third container has no specs to execute, thus both Node 18 containers are exiting without doing anything.

So you want to reconfigure and have _2_ jobs: one for Node v16 and another for v18

```yml
name: 'Web: UI Tests'

on: [workflow_dispatch, push]

jobs:
  run-ui-tests-v16:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run desktop tests
        uses: cypress-io/github-action@v5
        with:
            install: false
            working-directory: ./
            command: yarn test:cy:run
        env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Run mobile tests
        uses: cypress-io/github-action@v5
        with:
            install: false
            working-directory: ./
            command: yarn test:cy:run:mobile
        env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}

  run-ui-tests-v18:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run desktop tests
        uses: cypress-io/github-action@v5
        with:
            install: false
            working-directory: ./
            command: yarn test:cy:run
        env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}

      - name: Run mobile tests
        uses: cypress-io/github-action@v5
        with:
            install: false
            working-directory: ./
            command: yarn test:cy:run:mobile
        env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}
```
