### ISSUE TITLE
Running cypress-split with a matrix for both browsers + multiple containers

### ISSUE THREAD

**Issue by cbarratt** [bahmutov/cypress-split#76]
Hey,

This is a great piece of work, I want to acknowledge how handy this is 👍 

I was hoping to see if anyone else was attempting to figure this out:

for eg.

```
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
        browser: [chrome, edge]
```

if i want to run parallel containers, but also multiple browsers, it appears to act in an unexpected way.

In the above e.g, _all_ of the tests are split across all instances of the browsers + containers. 

My desired behaviour is to try and get 3 containers for chrome, 3 containers for edge and have the full test suite run across both browsers.

If anyone has any ideas, I'd be super appreciative 👍
